# Read the Docs Configuration File
#
# Reference:
#   https://docs.readthedocs.io/en/stable/config-file/v2.html for details
#
version: 2
formats: all
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
conda:
  environment: environment.yml
